version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file index-photos.yaml --s3-bucket aws-ablum-photo --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - index-photos.yaml
    - outputtemplate.yml
