AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  indexphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::043550019784:role/service-role/index-photos-role-6djaxaiu'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:Put'
      VpcConfig:
        SecurityGroupIds:
          - sg-cacb4cf4
        SubnetIds:
          - subnet-7349ff52
          - subnet-c44bb4f5
  Bucket1:
    Type: 'AWS::S3::Bucket'
