AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  photosearchaws:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::043550019784:role/service-role/photo-search-aws-role-rpwshxpq
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /search
            Method: GET
      VpcConfig:
        SecurityGroupIds:
          - sg-cacb4cf4
        SubnetIds:
          - subnet-20943f46
